### ISSUE TITLE
Windows style path is not treated as a valid command.

### ISSUE THREAD

**Issue by mashizora** [dsherret/dax#273]
In 0.40.0+, `command not found` error throws when calling an Windows executable file by Windows style path (separator is `\\`).

0.39.2 does not have this issue, It looks like an issue in `deno-which` implementation.

## Reproduction

```ts
import { $ } from "jsr:@david/dax@0.41.0";

await $`c:\\Windows\\explorer.exe`; // error
```

### Output

```
dax: c:\Windows\explorer.exe: command not found
error: Uncaught (in promise) Error: Exited with code: 127
            throw new Error(`Exited with code: ${code}`);
                  ^
    at CommandChild.pipedStdoutBuffer (https://jsr.io/@david/dax/0.41.0/src/command.ts:785:19)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

**Comment by dsherret** [comment]
This was fixed some time ago in https://github.com/dsherret/dax/pull/287
