### ISSUE TITLE
`deno task` fails with `Module not found`

### ISSUE THREAD

**Issue by SebastienGllmt** [dsherret/dax#296]
For some reason, I'm not able to get this library working with `deno task` despite other things like `deno eval` working.

```typescript
const child = await $`deno task <my-task>`;
```

fails with the following error

```
error: Module not found "file:///home/git/my-project/task".
error: Uncaught (in promise) Error: Exited with code: 1
    at CommandChild.pipedStdoutBuffer (file:///home/git/my-project/node_modules/.deno/dax-sh@0.42.0/node_modules/dax-sh/esm/mod.js:7950:19)
    at Object.runMicrotasks (ext:core/01_core.js:683:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:182:21)
```

This is on Deno 2.1.3

**Comment by dsherret** [comment]
Can you post a full reproduction with a deno.json?
